### ISSUE TITLE
Not support rollup v0.66

### ISSUE THREAD

**Issue by senntyou** [vuejs/rollup-plugin-vue#247]
- rollup `v0.66.6`
- rollup-plugin-vue `v4.3.2`
- error log:

```
(node:18674) UnhandledPromiseRejectionWarning: Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
    at error (/home/senntyou/space/senn/webpack-demo/node_modules/_rollup@0.66.6@rollup/dist/rollup.js:3460:30)
    at Module.error (/home/senntyou/space/senn/webpack-demo/node_modules/_rollup@0.66.6@rollup/dist/rollup.js:13358:9)
    at tryParse (/home/senntyou/space/senn/webpack-demo/node_modules/_rollup@0.66.6@rollup/dist/rollup.js:13019:16)
    at Module.setSource (/home/senntyou/space/senn/webpack-demo/node_modules/_rollup@0.66.6@rollup/dist/rollup.js:13092:33)
    at /home/senntyou/space/senn/webpack-demo/node_modules/_rollup@0.66.6@rollup/dist/rollup.js:21755:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
(node:18674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18674) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jonataswalker** [comment]
Not working with rollup `1.1.0` also.

**Comment by znck** [comment]
I've tested with v0.66 and v1.1.0, it's working. Please provide a repro if it's still not working.

**Comment by jonataswalker** [comment]
https://github.com/jonataswalker/rollup-repro

```shell
$ git clone ...
$ cd ... && npm i
$ npm run build
```

Ouput: `TypeError: vue is not a function` - `vue` is a reference to `rollup-plugin-vue`
