### ISSUE TITLE
Document new options and add recipies for common scanerios

### ISSUE THREAD

**Issue by znck** [vuejs/rollup-plugin-vue#208]
This would help to reduce questions/issues like #207 #203 

- [x] Minimal setup
- [ ] CSS extraction
- [ ] Typescript
- [ ] SSR 
- [ ] Component library

**Comment by aldarund** [comment]
cover ssr  usecase please :) Because for example with default options (css: true) & css in vue files it will produce unusable for ssr plugin.

**Comment by aldarund** [comment]
@znck i tried today solution for ssr from cookbook ( optimizeSSR option). But it just lead to errors in browser than. "_ssrNode" is not defined ,  _vm._ssrEscape is not a function ..

**Comment by znck** [comment]
You have to use commonjs build for SSR. 

I’ll try it once myself.

**Comment by aldarund** [comment]
@znck basically right now i have following config that is working with 4.1.4 version of plugin on both ssr and browser

**Comment by aldarund** [comment]
@znck basically right now i have following config that is working with 4.1.4 version of plugin on both ssr and browser
https://github.com/aldarund/vuetify-form-generator/blob/master/rollup.config.js
if i update to 4.2.0 -> it doesnt compile https://github.com/vuejs/rollup-plugin-vue/issues/207
if i add optimizeSSR ( was just wondering what it will actually do) option from cookbook -> it doesnt work in browser.
