### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by macu** [vuejs/rollup-plugin-vue#64]
After `npm i -D gulp-plugin-vue@v2.3.0-beta.3` and running my gulp vueify task:

```
Error: Cannot find module 'merge-options'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/s4l.divergent.io/node_modules/rollup-plugin-vue/dist/rollup-plugin-vue.common.js:33:36)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Same task works with v2.2.21 of this plugin, so I believe it is an issue with the beta.

**Comment by znck** [comment]
Fixed in [v2.3.0-beta.4](https://github.com/vuejs/rollup-plugin-vue/releases/tag/v2.3.0-beta.4)
